#!/bin/sh

set -u

usage() {
    echo 'Usage: ./webize.sh [OPTIONS]'
    echo '  Subcommands:'
    echo '      gallery             Generate a gallery index.htm'
    echo '      clean               Removes all index.htm'
    echo 'Examples: '
    echo '      # Generate a gallery index.htm for current directory and all descendent folders which contain images'
    echo '      ./webize.sh gallery .'
    echo
    echo '      # Generate a gallery index.htm for /path/to/camera/roll and all descendent folders which contain images, and open them in firefox'
    echo '      ./webize.sh gallery /path/to/camera/roll | xargs firefox'
    echo
    echo '      # Clean all index.htm for current directory and all descendent folders which contain images'
    echo '      ./webize.sh clean .'
    echo
    echo '      # Clean all index.htm for /path/to/camera/roll and all descendent folders which contain images'
    echo '      ./webize.sh clean /path/to/camera/roll'
}
# Exit if we got no options
if [ $# -eq 0 ]; then usage; exit 1; fi

# Get some options
while test $# -gt 0; do
    case "$1" in
        help|-h|--help)
            usage
            exit 0
            ;;
        gallery)
            GALLERY=1
            shift
            if test $# -gt 0; then
                export DIR="$1"
                shift
            else
                echo "Please specify a directory as a third argument. E.g. /path/to, or . for current directory" 1>&2
                exit 1
            fi
            ;;
        clean)
            CLEAN=1
            shift
            if test $# -gt 0; then
                export DIR="$1"
                shift
            else
                echo "Please specify a directory as a third argument. E.g. /path/to, or . for current directory" 1>&2
                exit 1
            fi
            ;;
        *)
            echo "Invalid option '$1'" 1>&2
            usage
            exit 1
            ;;
    esac
done

# Normalize, compile, and validation configuration
DIR=${DIR:-}
GALLERY=${GALLERY:-}
CLEAN=${CLEAN:-}
if [ ! -d "$DIR" ]; then
    echo "Directory does not exist: $DIR" 1>&2
    exit 1
fi
if [ "$DIR" = '.' ]; then
    DIR="$PWD"
fi

# Get directories with images
IMAGES_REGEX='\.gif|\.jpg|\.png|\.svg|\.webp'
dirs=$(
    find "$DIR" -type d | while read -r d; do
        if ls -p "$d" | grep -v '/' | grep -E "$IMAGES_REGEX" > /dev/null; then
            echo "$d"
        fi
    done | sort -n
)
if [ -z "$dirs" ]; then
    echo "No directories with images found." 1>&2
    exit 1
fi

# Generate index.htm in each directory
if [ -n "$GALLERY" ]; then
    echo "$dirs" | while read -r d; do
        indexHtm="$d/index.htm"
        imagesCsv=$(
            # Get only files, ignore the first line of ls -al, then parse file attributes into a single CSV. E.g. -rwxr-xr-x 1 packer packer 22681 2021-08-27T07:36:45+0000 webize -> webize,22681,2021-08-27T07:36:45+0000
            if echo "${OSTYPE:-}" | grep -qE 'darwin'; then
                cd "$d"
                files=$( stat -l -t '%Y-%m-%dT%H:%M:%S%z' * )
            else
                files=$( ls -al --time-style='+%Y-%m-%dT%H:%M:%S%z' -p "$d" )
            fi

            echo "$files" | grep -v '/' | grep -E "$IMAGES_REGEX" | while read -r l; do
                size=$( echo "$l" | awk '{print $5}' )
                dateiso=$( echo "$l" | awk '{print $6}' )
                filename=$( echo "$l" | awk '{print $1=$2=$3=$4=$5=$6=""; print $0}' | awk NF | sed 's/^[ ]*//g' )
                extension=$( echo "$filename" | sed 's/.*\(\.[^.]*\)$/\1/' )
                echo "$filename,$size,$dateiso,$extension"
            done
        )
        cat - > "$indexHtm" <<'EOF'
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        * { box-sizing: border-box; }
        html { width: 100%; height: 100%; background: #000; font-size: 0; }
        body { margin: 0; }
        menu { position: fixed; top: calc(100vh - 2vw - 4vw); bottom: 0; left: 0; right: 0; z-index: 1000; display: block; padding: 1vw; background: #000; opacity: 1; text-align: center; user-select: none; }
        menu fullscreen, menu stretchx, menu stretchy, menu tilesmaller, menu tilelarger, menu imagelabeller, menu pin, menu sort { display: inline-block; margin-right: 2vw; padding: 1vw; font-size: 2vw; line-height: 2vw; color: #fff; cursor: pointer; }
        content:before { content: ""; display: inline-block; vertical-align: middle; height: 100%; }
        content { display: block; text-align: center; }
        gallery { display: inline-block; width: 100%; text-align: center; vertical-align: middle; opacity: 0; }
        imageholder { position: relative; display: inline-block; margin: 0 auto; border: 1px solid transparent; }
        imageholder.highlight { border: 1px solid #fff; }
        imageholder info { position: absolute; top: 0; left: 0; right: 0; z-index: 0; }
        imageholder info label { display: block; background: #000; color: #fff; font-size: 1vw; line-height: 1vw; font-family: monospace; overflow: hidden; }
        imageholder img { display: inline-block; margin: 0 auto; width: 100%; height: auto; }
    </style>
</head>
<body>
    <menu>
        <fullscreen title="Full Screen (F)" alt="Full Screen (F)">💻</fullscreen>
        <stretchx title="Stretch horizontal (X)" alt="Stretch horizontal (X)">↔️</stretchx>
        <stretchy title="Stretch vertical (Y)" alt="Stretch vertical (Y)">↕️</stretchy>
        <tilesmaller title="Tile smaller (-)" alt="Tile smaller (-)">🐜</tilesmaller>
        <tilelarger title="Tile larger (+)" alt="Tile larger (=)">🦕</tilelarger>
        <imagelabeller title="Show / Hide label (L)" alt="Show / Hide label (L)">🏷</imagelabeller>
        <sort title="Toggle sort mode" alt="Toggle sort mode"></sort><!-- innerHTML will be injected on DOMContentLoaded -->
        <pin title="Pin / Unpin menu (P)" alt="Pin / Unpin menu (P)">📌</pin>
    </menu>
    <content>
        <gallery></gallery>
    </content>
    <script>
        // Images
        const imagesCsv = `
EOF
    echo "$imagesCsv" >> "$indexHtm"
cat - >> "$indexHtm" <<'EOF'
`;
        // Parse into image objects
        const imageObjects = (function(imagesCsv) {
            var imageObjects = [];

            var split = imagesCsv.split(/\n/).filter(function (v) { return v !== ''; });
            for (var i = 0; i < split.length; i++) {
                var fileAttr = split[i].split(/,/);
                imageObjects.push({
                    filename: fileAttr[0],
                    size: fileAttr[1],
                    dateiso: fileAttr[2],
                    extension: fileAttr[3],
                 });
            }

            return imageObjects;
        }(imagesCsv));

        var Helpers = (function () {
            return {
                htmlEntities: function htmlEntities(str) {
                    return String(str).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/'/g, '&#39;').replace(/"/g, '&#34;').replace(/ /g, '&nbsp;').replace(/\r?\n/g, '<br />');
                },
            };
        })();

        var menu = (function() {
            var rootElement = document.getElementsByTagName("menu")[0];
            var isPinned = true;
            var isMouseEntered = false;
            var sortModeIndex = 0;
            var sortModes = [
                {
                    "label": "🔤🔼",
                    "keys": [
                        "filename"
                    ],
                    "order": "asc",
                },
                {
                    "label": "🔤🔽",
                    "keys": [
                        "filename"
                    ],
                    "order": "desc",
                },
                {
                    "label": "📆🔼",
                    "keys": [
                        "dateiso"
                    ],
                    "order": "asc",
                },
                {
                    "label": "📆🔽",
                    "keys": [
                        "dateiso"
                    ],
                    "order": "desc",
                },
                {
                    "label": "🍱🔼",
                    "keys": [
                        "extension"
                    ],
                    "order": "asc",
                },
                {
                    "label": "🍱🔽",
                    "keys": [
                        "extension"
                    ],
                    "order": "desc",
                },
                {
                    "label": "🔢🔼",
                    "keys": [
                        "size"
                    ],
                    "order": "asc",
                },
                {
                    "label": "🔢🔽",
                    "keys": [
                        "size"
                    ],
                    "order": "desc",
                }
            ];

            // Init
            document.addEventListener("DOMContentLoaded", function(event) {
                var sort = document.getElementsByTagName("sort")[0];
                sort.innerHTML = sortModes[sortModeIndex].label;
            });

            rootElement.addEventListener("mouseenter", function(e) {
                isMouseEntered = true;
                rootElement.style.opacity = "1";
                rootElement.style.paddingTop = "";
            });
            rootElement.addEventListener("mouseleave", function(e) {
                isMouseEntered = false;
                if (!isPinned) {
                    rootElement.style.opacity = "0";
                    rootElement.style.paddingTop = "100vh"; // Push the menu items out of viewport
                }
            });

            var toggleFullscreenHandler = function() {
                document.documentElement.requestFullscreen();
            };
            rootElement.getElementsByTagName("fullscreen")[0].addEventListener("click", function(e) {
                toggleFullscreenHandler();
            });

            rootElement.getElementsByTagName("stretchx")[0].addEventListener("click", function(e) {
                gallery.mode = "stretchx";
            });
            rootElement.getElementsByTagName("stretchy")[0].addEventListener("click", function(e) {
                gallery.mode = "stretchy";
            });
            rootElement.getElementsByTagName("tilesmaller")[0].addEventListener("click", function(e) {
                gallery.mode = "tilesmaller";
            });
            rootElement.getElementsByTagName("tilelarger")[0].addEventListener("click", function(e) {
                gallery.mode = "tilelarger";
            });

            var toggleLabelHandler = function() {
                var imagelabeller = document.getElementsByTagName("imagelabeller")[0];
                if (gallery.isImagesLabelled) {
                    gallery.isImagesLabelled = false;
                    imagelabeller.style.opacity = "0.5";
                }else {
                    gallery.isImagesLabelled = true;
                    imagelabeller.style.opacity = "1.0";
                }
            };
            rootElement.getElementsByTagName("imagelabeller")[0].addEventListener("click", function(e) {
                toggleLabelHandler();
            });

            var togglePinHandler = function() {
                var pin = document.getElementsByTagName("pin")[0];
                if (isPinned) {
                    isPinned = false;
                    if (isMouseEntered) {
                        rootElement.style.opacity = "";
                        rootElement.style.paddingTop = "";
                    }else {
                        rootElement.style.opacity = "0";
                        rootElement.style.paddingTop = "100vh"; // Push the menu items out of viewport
                    }
                    pin.style.opacity = "0.5";
                }else {
                    isPinned = true;
                    rootElement.style.opacity = "1.0";
                    rootElement.style.paddingTop = "";
                    pin.style.opacity = "1.0";
                }
            };
            rootElement.getElementsByTagName("pin")[0].addEventListener("click", function(e) {
                togglePinHandler();
            });

            var toggleSortMode = function() {
                var sort = document.getElementsByTagName("sort")[0];

                sortModeIndex = sortModeIndex === sortModes.length - 1 ? 0 : sortModeIndex + 1;
                sort.innerHTML = sortModes[sortModeIndex].label;
                gallery.sort(sortModes[sortModeIndex]);
            };
            rootElement.getElementsByTagName("sort")[0].addEventListener("click", function(e) {
                toggleSortMode();
            });

            var keyHandler = function(event) {
                var ele = event.target || event.srcElement;
                var keyCode = event.keyCode || event.charCode;

                // f key
                if (keyCode === 70) {
                    toggleFullscreenHandler();
                }
                // l key
                if (keyCode === 76) {
                    toggleLabelHandler();
                }
                // s key
                if (keyCode === 83) {
                    toggleSortMode();
                }
                // p key
                if (keyCode === 80) {
                    togglePinHandler();
                }

                // console.log(keyCode);
            };

            return {
                keyHandler: keyHandler,
                get sortMode() {
                    return sortModes[sortModeIndex];
                },
                togglePinHandler: togglePinHandler
            };
        })();

        var gallery = (function(imageObjs) {
            var rootElement = document.getElementsByTagName("gallery")[0];

            // Config
            var imageObjects = imageObjs;

            // State
            var mode = "tilesmaller";
            var images;
            var activeImageIndex = 0;
            var tileFactor = 7;
            const minTileFactor = 2;
            const maxTileFactor = 10;
            var isImagesLabelled = true;

            // Init
            document.addEventListener("DOMContentLoaded", function(event) {
                createImageComponents(menu.sortMode);
                setMode(mode);
                setTimeout(function() {
                    rootElement.style.opacity = "1.0";
                }, 1000);
            });

            var createImageComponents = function(sortMode) {
                // Sort image objects by the given sort mode object
                for (var i = 0, k; i < sortMode.keys.length; i++) {
                    k = sortMode.keys[i];
                    imageObjects.sort(function(a, b) {
                        if (sortMode.order === 'asc') {
                            if (a[k] < b[k]) {
                                return -1;
                            }
                            if (a[k] > b[k]) {
                                return 1;
                            }
                        }
                        if (sortMode.order === 'desc') {
                            if (a[k] < b[k]) {
                                return 1;
                            }
                            if (a[k] > b[k]) {
                                return -1;
                            }
                        }
                        return 0;
                    });
                }
                // console.log(sortMode);
                // console.log(imageObjects);

                // Generate new image components
                var imageComponents = [];
                // E.g.
                // <imageholder>
                //   <info>
                //     <label>$i</label>
                //   </info>
                //   <img src=\"$i\" />
                // </imageholder>
                var imageholder, info, label, img;
                for (var i = 0; i < imageObjects.length; i++) {
                    imageholder = document.createElement("imageholder");
                    info = document.createElement("info");
                    label = document.createElement("label");
                    label.innerHTML = Helpers.htmlEntities(imageObjects[i].filename);
                    img = document.createElement("img");
                    img.src = encodeURIComponent(imageObjects[i].filename);
                    img.alt = Helpers.htmlEntities(imageObjects[i].filename);

                    info.appendChild(label);
                    imageholder.appendChild(info);
                    imageholder.appendChild(img);

                    imageComponents.push(imageholder);
                }

                // Add events - Set as element of interest while clicking or focusing
                var clickOrFocusHandler = function(e) {
                    if (mode === "stretchx" || mode === "stretchy" ) {
                        // Tap on image should toggle the menu
                        menu.togglePinHandler();
                    }
                    var ele = event.target || event.srcElement;
                    var imageholder = ele.parentNode;
                    var idx = Array.from(imageholder.parentNode.children).indexOf(imageholder); // Wrapper
                    setActiveImageIndex(idx);
                    setMode("stretchy");
                };
                for (var i = 0; i < imageComponents.length; i++) {
                    imageComponents[i].addEventListener("click", clickOrFocusHandler);
                    imageComponents[i].addEventListener("focus", clickOrFocusHandler);
                }

                // Replace gallery with new image components
                rootElement.innerHTML = '';
                for (var i = 0; i < imageComponents.length; i++) {
                    rootElement.appendChild(imageComponents[i]);
                }

                // Cache the image elements
                images = rootElement.getElementsByTagName("img");
            };

            var stretchx = function() {
                for (var i = 0; i < images.length; i++) {
                    images[i].parentNode.style.display = "inline-block";
                    images[i].parentNode.style.width = "100vw";
                    images[i].parentNode.style.height = "100vh";
                    images[i].style.width = "100%";
                    images[i].style.height = "auto";
                }
                setActiveImageIndex(activeImageIndex, true);
            };

            var stretchy = function() {
                for (var i = 0; i < images.length; i++) {
                    images[i].parentNode.style.display = "inline-block";
                    images[i].parentNode.style.width = "100vw";
                    images[i].parentNode.style.height = "100vh";
                    images[i].style.width = "auto";
                    images[i].style.height = "100%";
                }
                setActiveImageIndex(activeImageIndex, true);
            };

            var tilesmaller = function(preserve) {
                if (!preserve) {
                    tileFactor = tileFactor === maxTileFactor ? maxTileFactor : tileFactor + 1;
                }
                for (var i = 0; i < images.length; i++) {
                    images[i].parentNode.style.display = "inline-block";
                    images[i].parentNode.style.verticalAlign = "top";
                    images[i].parentNode.style.width = "calc(100vw / " + tileFactor + ")";
                    images[i].parentNode.style.height = "calc(100vw / " + tileFactor + ")";
                    if (images[i].naturalWidth >= images[i].naturalHeight) {
                        // Landscape
                        images[i].style.width = "100%";
                        images[i].style.height = "auto";
                    }else {
                        // Portrait
                        images[i].style.width = "auto";
                        images[i].style.height = "100%";
                    }
                }
                setActiveImageIndex(activeImageIndex, true);
            };

            var tilelarger = function(preserve) {
                if (!preserve) {
                    tileFactor = tileFactor === minTileFactor ? minTileFactor : tileFactor - 1;
                }
                for (var i = 0; i < images.length; i++) {
                    images[i].parentNode.style.display = "inline-block";
                    images[i].parentNode.style.verticalAlign = "top";
                    images[i].parentNode.style.width = "calc(100vw / " + tileFactor + ")";
                    images[i].parentNode.style.height = "calc(100vw / " + tileFactor + ")";
                    if (images[i].naturalWidth >= images[i].naturalHeight) {
                        // Landscape
                        images[i].style.width = "100%";
                        images[i].style.height = "auto";
                    }else {
                        // Portrait
                        images[i].style.width = "auto";
                        images[i].style.height = "100%";
                    }
                }
                setActiveImageIndex(activeImageIndex, true);
            };

            var resetImagesStyles = function() {
                for (var i = 0; i < images.length; i++) {
                    var imageholder = images[i].parentNode;
                    imageholder.className = "";
                }
            }

            var showAllImageLabels = function() {
                for (var i = 0; i < images.length; i++) {
                    var imageholder = images[i].parentNode;
                    imageholder.getElementsByTagName("label")[0].style.opacity = "1.0";
                }
            };
            var hideAllImageLabels = function() {
                for (var i = 0; i < images.length; i++) {
                    var imageholder = images[i].parentNode;
                    imageholder.getElementsByTagName("label")[0].style.opacity = "0.0";
                }
            };

            var setMode = function(value, preserve) {
                var modePrev = mode;
                if (value) {
                    mode = value;
                }
                switch (value) {
                    case "stretchx":
                        stretchx();
                        break;
                    case "stretchy":
                        stretchy();
                        break;
                    case "tilesmaller":
                        if (modePrev === "tilesmaller" || modePrev === "tilelarger") {
                            tilesmaller(preserve);
                        }else {
                            tilesmaller(true);
                        }
                        break;
                    case "tilelarger":
                        if (modePrev === "tilesmaller" || modePrev === "tilelarger") {
                            tilelarger(preserve);
                        }else {
                            tilelarger(true);
                        }
                        break;
                    default:
                        break;
                }
            };

            var setActiveImageIndex = function(value, scroll) {
                activeImageIndex = value;
                var imageholder;
                for (var i = 0; i < images.length; i++) {
                    imageholder = images[i].parentNode;
                    imageholder.className = "";
                }
                imageholder = images[activeImageIndex].parentNode;
                if (mode === "tilesmaller" || mode === "tilelarger") {
                    imageholder.className = "highlight";
                }
                if (scroll) {
                    scrollToActiveImage();
                }
                console.log("[setActiveImageIndex] activeImageIndex: " + activeImageIndex);
            };

            var setPreviousImageAsActiveImage = function() {
                if (activeImageIndex <= 0) {
                    // Go to end
                    setActiveImageIndex(images.length - 1, true);
                }else {
                    var imageholder = images[activeImageIndex].parentNode;
                    var idx = Array.from(imageholder.parentNode.children).indexOf(imageholder); // Wrapper
                    idx -= 1;
                    var scroll = (function(images, idx) {
                        const viewportHeight = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0);
                        if (images[idx].parentNode.offsetTop < window.scrollY) {
                            return true;
                        }
                        return false;
                    }(images, idx));
                    setActiveImageIndex(idx, scroll);
                }
            };

            var setNextImageAsActiveImage = function() {
                if (activeImageIndex >= images.length - 1) {
                    // Go to start
                    setActiveImageIndex(0, true);
                }else {
                    var imageholder = images[activeImageIndex].parentNode;
                    var idx = Array.from(imageholder.parentNode.children).indexOf(imageholder); // Wrapper
                    idx += 1;
                    var scroll = (function(images, idx) {
                        const viewportHeight = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0);
                        if (images[idx].parentNode.offsetTop + images[idx].parentNode.offsetHeight > window.scrollY + viewportHeight) {
                            return true;
                        }
                        return false;
                    }(images, idx));
                    setActiveImageIndex(idx, scroll);
                }
            };

            var setPreviousRowImageAsActiveImage = function() {
                var imageholder = images[activeImageIndex].parentNode;
                var idx = Array.from(imageholder.parentNode.children).indexOf(imageholder); // Wrapper
                var rem = images.length % tileFactor;
                console.log('rem: ' + rem);
                if (rem > 0 && activeImageIndex + 1 >= images.length - rem) {
                    // On the last row with a non-full row. We should scroll less than tileFactor thumbnails
                    var missing = tileFactor - rem;
                    var missingFromCenter = Math.floor(missing / 2);
                    console.log('missing: ' + missing + ', missingFromCenter: ' + missingFromCenter);
                    idx -= tileFactor - missingFromCenter;
                }else {
                    idx -= tileFactor;
                }
                if (idx <= 0) {
                    idx = 0;
                }
                var scroll = (function(images, idx) {
                    const viewportHeight = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0);
                    if (images[idx].parentNode.offsetTop < window.scrollY) {
                        return true;
                    }
                    return false;
                }(images, idx));
                setActiveImageIndex(idx, scroll);
            };

            var setNextRowImageAsActiveImage = function() {
                var imageholder = images[activeImageIndex].parentNode;
                var idx = Array.from(imageholder.parentNode.children).indexOf(imageholder); // Wrapper
                var rem = images.length % tileFactor;
                var missing = tileFactor - rem;
                var missingFromCenter = Math.floor(missing / 2);
                console.log('rem: ' + rem);
                console.log('missing: ' + missing + ', missingFromCenter: ' + missingFromCenter);
                if (activeImageIndex + tileFactor + 1 >= images.length - rem) {
                    // On second last row
                    if ((activeImageIndex + 1) % tileFactor > 0 && (activeImageIndex + 1) % tileFactor <= missingFromCenter) {
                        // Scroll to first image on last row
                        console.log("Scrolling to first image of last row");
                        idx = images.length - 1 - rem + 1;
                    }else {
                        // On the row just prior to a non-full last row. We should scroll less than tileFactor thumbnails
                        idx += tileFactor - missingFromCenter;
                    }
                }else {
                    idx += tileFactor;
                }
                if (idx >= images.length - 1) {
                    idx = images.length - 1;
                }
                var scroll = (function(images, idx) {
                    const viewportHeight = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0);
                    if (images[idx].parentNode.offsetTop + images[idx].parentNode.offsetHeight > window.scrollY + viewportHeight) {
                        return true;
                    }
                    return false;
                }(images, idx));
                setActiveImageIndex(idx, scroll);
            };

            var setPreviousPageImageAsActiveImage = function() {
                const imageholderMaxHeight = (function(images) {
                    // Find the tallest image in the first row
                    var max = 0, lastmax = 0;
                    for (var i = 0; i < images.length - 1 && i < tileFactor; i++) {
                        tmp =  images[i].parentNode.offsetHeight;
                        max = tmp > max ? tmp : max;
                    }
                    return max;
                })(images);
                const viewportHeight = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0);
                const rows = Math.floor(viewportHeight / imageholderMaxHeight); // Number of rows of thumbnails that fit in viewport without being cut off
                console.log('rows: ' + rows);

                var imageholder = images[activeImageIndex].parentNode;
                var idx = Array.from(imageholder.parentNode.children).indexOf(imageholder); // Wrapper
                idx -= tileFactor * (rows - 1)
                if (idx <= 0) {
                    idx = 0;
                }
                setActiveImageIndex(idx, true);
            };
            var setNextPageImageAsActiveImage = function() {
                const imageholderMaxHeight = (function(images) {
                    // Find the tallest image in the first row
                    var max = 0, lastmax = 0;
                    for (var i = 0; i < images.length - 1 && i < tileFactor; i++) {
                        tmp =  images[i].parentNode.offsetHeight;
                        max = tmp > max ? tmp : max;
                    }
                    return max;
                })(images);
                const viewportHeight = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0);
                const rows = Math.floor(viewportHeight / imageholderMaxHeight); // Number of rows of thumbnails that fit in viewport without being cut off
                console.log('rows: ' + rows);

                var imageholder = images[activeImageIndex].parentNode;
                var idx = Array.from(imageholder.parentNode.children).indexOf(imageholder); // Wrapper
                idx += tileFactor * (rows - 1); // If starting at row 1, and screen only fits 5 rows, with 6th row cut off, scroll to first image of 5th row

                if (idx >= images.length - 1) {
                    idx = images.length - 1;
                }
                setActiveImageIndex(idx, true);
            };

            var scrollToActiveImage = function() {
                console.log("Scrolling to active image, index: " + activeImageIndex + ", offsetTop: " + images[activeImageIndex].parentNode.offsetTop);
                window.scroll(0, images[activeImageIndex].parentNode.offsetTop);
            };

            var setScopeImageAsActiveImage = function() {
                if (mode === "stretchx" || mode === "stretchy" ) {
                    for (var i = images.length - 1; i >= 0; i--) {
                        if (images[i].parentNode.offsetTop < window.scrollY) {
                            console.log("Setting active image: " + i);
                            setActiveImageIndex(i);
                            break;
                        }
                    }
                }
            }
            // Set element of interest while scrolling
            rootElement.addEventListener("wheel", function(e) {
                setScopeImageAsActiveImage();
            });

            var sort = function(sortMode) {
                createImageComponents(sortMode);
                setMode(mode, true);
            }

            var keyHandler = function(event) {
                var ele = event.target || event.srcElement;
                var keyCode = event.keyCode || event.charCode;
                var key = event.key;
                console.log('keyCode: ' + keyCode + ', key: ' + key);

                // LEFT arrow key
                if (keyCode === 37) {
                    setPreviousImageAsActiveImage();
                    event.preventDefault();
                }
                // RIGHT arrow key
                if (keyCode === 39) {
                    setNextImageAsActiveImage();
                    event.preventDefault();
                }
                // UP arrow key
                if (keyCode === 38) {
                    if (mode === "tilesmaller" || mode === "tilelarger") {
                        setPreviousRowImageAsActiveImage();
                    }else {
                        setPreviousImageAsActiveImage();
                    }
                    event.preventDefault();
                }
                // DOWN arrow key
                if (keyCode === 40) {
                    if (mode === "tilesmaller" || mode === "tilelarger") {
                        setNextRowImageAsActiveImage();
                    }else {
                        setNextImageAsActiveImage();
                    }
                    event.preventDefault();
                }
                // PageUp
                if (keyCode === 33) {
                    if (mode === "tilesmaller" || mode === "tilelarger") {
                        setPreviousPageImageAsActiveImage();
                        event.preventDefault();
                    }else {
                        setScopeImageAsActiveImage();
                    }
                }
                // PageDown
                if (keyCode === 34) {
                    if (mode === "tilesmaller" || mode === "tilelarger") {
                        setNextPageImageAsActiveImage();
                        event.preventDefault();
                    }else {
                        setScopeImageAsActiveImage();
                    }
                }
                // Home
                if (keyCode === 36) {
                    setActiveImageIndex(0, true);
                }
                // End
                if (keyCode === 35) {
                    setActiveImageIndex(images.length - 1, true);
                }
                // ENTER key
                if (keyCode === 13) {
                    setMode("stretchy");
                    event.preventDefault();
                }
                // BACKSPACE key
                if (keyCode == 8) {
                    setMode("tilesmaller");
                    event.preventDefault();
                }
                // SPACE key
                if (keyCode == 32) {
                    setNextImageAsActiveImage();
                    event.preventDefault();
                }
                // ESC key (if in full screen, escapes full screen first, goes back to tiled view, and tiles smaller)
                if (keyCode === 27) {
                    setMode("tilesmaller");
                    event.preventDefault();
                }

                // x key
                if (keyCode === 88) {
                    setMode("stretchx");
                    event.preventDefault();
                }
                // y key
                if (keyCode === 89) {
                    setMode("stretchy");
                    event.preventDefault();
                }
                // - key
                if (keyCode === 173) {
                    setMode("tilesmaller");
                    event.preventDefault();
                }
                // = key
                if (keyCode === 61) {
                    setMode("tilelarger");
                    event.preventDefault();
                }

                // console.log(keyCode);
            };

            return {
                get mode() {
                    return mode;
                },
                set mode(value) {
                    setMode(value);
                },
                get isImagesLabelled() {
                    return isImagesLabelled;
                },
                set isImagesLabelled(value) {
                    isImagesLabelled = value;
                    if (isImagesLabelled) {
                        showAllImageLabels();
                    }else {
                        hideAllImageLabels();
                    }
                },
                sort: sort,
                keyHandler: keyHandler
            };
        })(imageObjects);

        // App Events
        window.addEventListener("keydown", function (event) {
            menu.keyHandler(event);
            gallery.keyHandler(event);
        });
    </script>
</body>
</html>
EOF
        echo "$indexHtm"
    done
fi

# Remove index.htm in each directory
if [ -n "$CLEAN" ]; then
    echo "$dirs" | while read -r d; do
        indexHtm="$d/index.htm"
        if [ -f "$indexHtm" ]; then
            rm -f "$indexHtm"
            echo "$indexHtm"
        fi
    done
fi
